services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: '../src/Apps/'
    exclude:
      - '../src/Apps/**/Entity/'
      - '../src/Apps/**/Resources/'
      - '../src/Apps/**/Migrations/'

  App\Components\:
    resource: '../src/Components/'
    exclude:
      - '../src/Components/**/Entity/'
      - '../src/Components/**/Resources/'
      - '../src/Components/**/Migrations/'
